### ISSUE TITLE
Unicode quotes & NER

### ISSUE THREAD

**Issue by dhrubins** [Ulflander/compendium-js#1]
It looks like smartquotes like (“ and ”) cause an issue with entity recognition. I haven't tried it with other unicode characters or other tasks.
```
compendium.analyse("I just started using a package called \"Compendium\" and find that it works quite well.")
compendium.analyse("However, smartquotes make \u201CCompendium\u201D sad just like the rest of us.")
```
At least there's an easy workaround:
```
text = text.replace(/[\u2018\u2019]/g, "'"); // change ‘ and ’ to '
text = text.replace(/[\u201C\u201D]/g, '"'); // change “ and ” to "
text = text.replace(/[\u2013\u2014]/g, '"'); // change – to -
text = text.replace(/[\u2026]/g, '...');     // change … to ...
```

**Comment by Ulflander** [comment]
Hi!

Thanks a lot for that feedback! 
I'll add the replacements into a "decoder" that I added in the latest version, and will add a few dedicated tests. Will push it tonight!

Cheers,
Xav

**Comment by Ulflander** [comment]
Fixed! See demo here: http://laumonier.co/compendium-js/example/example.html

Thanks again!
