### ISSUE TITLE
Sentence detection fails at simple punctuation

### ISSUE THREAD

**Issue by giorgio79** [Ulflander/compendium-js#10]
![image](https://user-images.githubusercontent.com/283347/34338613-c9ec019c-e96a-11e7-86df-e35f86b07a4b.png)

**Comment by artdent** [comment]
It looks like the sentence boundary detector thinks that 'me' is an abbreviation. https://github.com/Ulflander/compendium-js/blob/1cd57b7f724dbeb3a46a70f99276adf6e2fe65fd/src/compendium-en.js#L172

**Comment by Ulflander** [comment]
Fixed in v0.0.28. Thanks for the report guys!
