### ISSUE TITLE
Is there anyway to configure compendium to run only selected analysis

### ISSUE THREAD

**Issue by sugang** [Ulflander/compendium-js#8]
Hi there again - I was wondering if it's possible to configure compendium to only run selected analysis. In my particular use case I only want to run negation detection; however if I run compendium on a document with about 700 words, it takes about 1 second in browser. I was wondering whether there are any ways to speed up this process. Thanks!

**Comment by Ulflander** [comment]
Hey there, are you still using compendium? If so I'll try to do something for your performance issue. Cheers, Ulf.

**Comment by sugang** [comment]
Yes! This is the best javascript based NLP lib so far. Thank you!

**Comment by Ulflander** [comment]
Hi! 

It took quite some time but here we are! You can now skip some detectors (see [some doc clues in readme](https://github.com/Ulflander/compendium-js#skipping-detectors), in particular sentiment analysis, entity extraction, type and numeric detection. It should help speed up a bit the analysis. Let me know if it's fine enough for you!

Cheers,
Ulf
